trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'frontend/*'

stages:
- stage: BuildStage
  displayName: Build
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
      demands:
      - npm
    steps:
    - task: Npm@1
      displayName: 'Run npm install'
      inputs:
        workingDir: 'frontend'
        verbose: true

    - task: Npm@1
      displayName: 'Build App'
      inputs:
        command: 'custom'
        customCommand: 'run build'
        workingDir: 'frontend'
        verbose: true

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/frontend/dist'
        includeRootFolder: false
        archiveFile: '$(Build.ArtifactStagingDirectory)/node-cosmos-graphql-ui-$(Build.BuildId).zip'


    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/node-cosmos-graphql-ui-$(Build.BuildId).zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: DeployStage
  displayName: Deploy
  dependsOn: BuildStage
  jobs:
    - deployment: DeployJob
      pool:
        vmImage: 'ubuntu-latest'
      environment: 'Production UI'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: ExtractFiles@1
              displayName: Extract Files
              inputs:
                archiveFilePatterns: '$(Pipeline.Workspace)/drop/node-cosmos-graphql-ui-$(Build.BuildId).zip'
                destinationFolder: '$(Pipeline.Workspace)/dist'
                cleanDestinationFolder: true
            - task: AzureCLI@2
              displayName: Deploy to Azure
              inputs:
                azureSubscription: $(AzureSubscription)
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  az storage blob upload-batch — account-name $(AzureStorageName) account-key $(AzureStorageKey) — destination ‘$web’ — source '$(Pipeline.Workspace)/dist'