trigger:
  branches:
    include:
      - master
  paths:
    include:
      - 'backend/*'

pool:
  vmImage: 'ubuntu-latest'
  demands:
  - npm

steps:
- task: Npm@1
  displayName: 'Run npm install'
  inputs:
    verbose: false

- script: |
    npm run build
  displayName: 'Build Project'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(AzureSubscription)
    appType: 'webAppLinux'
    WebAppName: $(AzureAppServiceName)
    packageForLinux: '$(Build.SourcesDirectory)/dist'
    RuntimeStack: 'NODE|12-lts'
    StartupCommand: 'node server.js'